image: alpine/edge
packages:
  - hugo
  - rsync
  - curl
  - jq
sources:
  - https://github.com/expertanalytics/website
environment:
  prod_repo: git@github.com:expertanalytics/expertanalytics.github.io.git
  ssh_command: ssh -o StrictHostKeyChecking=no
secrets:
  - 38580985-01bc-4f34-a3dc-011d85f691bd
  - a53bfb84-63e8-4b9a-9636-704262834e2d
tasks:
  - setup: |
      rm -rf public
  - build: |
      cd website
      hugo --minify --destination=../public || exit 1
  - deploy: |
      if [ $GITHUB_REF = refs/heads/master ]; then
          curl -H @.github_auth_header -H "Accept: application/vnd.github.ant-man-preview+json" \
              -X POST https://api.github.com/repos/expertanalytics/website/deployments \
              -d "{\"ref\": \"$GITHUB_REF\", \"auto_merge\": false, \"required_contexts\": []}" \
              | jq -r .statuses_url > .statuses_url
          cd public
          echo expertanalytics.no > CNAME
          git init
          git config user.name builds.sr.ht
          git config user.email post@expertanalytics.no
          git config core.sshCommand "$ssh_command"
          git add .
          git commit -m 'Deploy from sr.ht'
          git push $prod_repo @:master --force
          cd ~
          env_url=https://expertanalytics.no/
      else
          env_name=$(echo ${GITHUB_REF##*/} | tr '[:upper:]' '[:lower:]')
          curl -H @.github_auth_header -H "Accept: application/vnd.github.ant-man-preview+json" \
              -X POST https://api.github.com/repos/expertanalytics/website/deployments \
              -d "{\"ref\": \"$GITHUB_REF\", \"environment\": \"pr-$env_name\", \"auto_merge\": false, \"required_contexts\": []}" \
              | jq -r .statuses_url > .statuses_url
          env_url=http://$env_name.pr.dev.xal.no/
          rsync -e "$ssh_command" --delete -rv public/ deploy@dev.xal.no:www/pr/$env_name
      fi
      curl -H @.github_auth_header -H "Accept: application/vnd.github.ant-man-preview+json" \
          -X POST $(cat .statuses_url) \
          -d "{\"state\": \"success\", \"environment_url\": \"$env_url\", \"log_url\": \"$JOB_URL#task-deploy\"}"
