baseURL = "https://expertanalytics.no/"
languageCode = "en-us"
title = "Expert Analytics"
summaryLength = 500
googleAnalytics = "G-BL3R31765C"

[params]
copyright = "© Expert Analytics AS"
director = "ola"

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true

[taxonomies]
  service = "services"
  project = "projects"
