baseURL = "https://expertanalytics.no/"
languageCode = "en-us"
title = "Expert Analytics"

[params]
copyright = "© Expert Analytics AS"

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
